### ISSUE TITLE
Custom Multiblock Structure

### ISSUE THREAD

**Issue by RehabCZ** [fonnymunkey/BQ-RLCraftExpansion#2]
I have issue with creating MBS Quest on Combustion Chamber from Magneticraft
After building Multiblock I can't click on keyBlock with selected item and multiblock doesn't detect as completed.
I'm using the latest version of **BQ** and **BQ - Multiblock and Structure Integration**

**This is my txt file** (combustion_chamber.txt)

`wildcard,magneticraft:multiblock_parts:5,wildcard
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,keyBlock,minecraft:brick_block:*
.
wildcard,magneticraft:multiblock_parts:5,wildcard
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
`

**And my quest config**

BLOCK SECTION
`
amount = 1
blockID = magneticraft:big_combustion_chamber
meta = -1
oreDict = "blankspace"
`

TASK SECTION
`
fileNames = combustion_chamber.txt
gameStageCompat = 0
gameStageName = "blankspace"
height = 2
imageLocation = "blankspace"
item = Air
length = 4
name = Bigger Combustion Chamber
useImage = 0
width = 3
wildcardOptimization = 1
`

Github may break formating of txt file so i attached original file
[combustion_chamber.txt](https://github.com/fonnymunkey/BQ_Multiblock_Structure_Integration/files/5938788/combustion_chamber.txt)

**Comment by fonnymunkey** [comment]
Your second level of blocks, you have one line of brick blocks too many.
Should be: 
```
wildcard,magneticraft:multiblock_parts:5,wildcard
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:* 
```

Not:
```
wildcard,magneticraft:multiblock_parts:5,wildcard
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
minecraft:brick_block:*,minecraft:brick_block:*,minecraft:brick_block:*
```

I tested it with this fixed, and all your other settings the same, and it worked fine for me.

**Comment by RehabCZ** [comment]
Thank u so much :D

If u don't mind i have one last question about understanding parameters

**height** is blue line
**width** is orange line
**length** is red line

![Inked2021-02-08_11 39 35_LI](https://user-images.githubusercontent.com/71905162/107208985-8f349980-6a02-11eb-96fd-be63b5e224af.jpg)

**Comment by fonnymunkey** [comment]
Height is self-explanatory yes, length and width relate to the layout in the .txt files, not the in-world blocks.
The mod automatically checks for all possible rotations in the game.
Width is left-right in the .txt file, length is up-down, and height is separated with "."

**Comment by RehabCZ** [comment]
That's what i needed to know.
I really appreciate your help and this awesome mod... you saved me

**Comment by RehabCZ** [comment]
Hi it's me again... I'm sorry for bothering you
But I'm having issues with **Small steam engine** from **Magneticraft**
Although i checked txt file and task settings i haven't find the issue yet...

**Txt file is here:**
[steam_engine.txt](https://github.com/fonnymunkey/BQ_Multiblock_Structure_Integration/files/5972022/steam_engine.txt)

**And BQ Task settings:**
height=4
length=4
width=3
fileNames=steam_engine.txt
item=air
wildcardOptimization=1
BlockID=magneticraft:steam_engine
meta=-1

**Comment by fonnymunkey** [comment]
Your last 3 "magneticraft:multiblock_parts" don't have metadata after them (:* or :0 or :1 etc)
I assume thats the issue.

**Comment by RehabCZ** [comment]
Already tried that...
Maybe there is issue with Column Block, that can be turn to different axis

**Comment by fonnymunkey** [comment]
I tested it on my install, I changed
```
wildcard,wildcard,wildcard
wildcard,wildcard,magneticraft:multiblock_parts
wildcard,wildcard,magneticraft:multiblock_parts
wildcard,wildcard,magneticraft:multiblock_parts
```
To
```
wildcard,wildcard,wildcard
wildcard,wildcard,magneticraft:multiblock_parts:0
wildcard,wildcard,magneticraft:multiblock_parts:0
wildcard,wildcard,magneticraft:multiblock_parts:0
```
And it works fine.

I also checked rotation of the columns, while the machine itself wont form if theyre oriented wrong, the task does not care about orientation.

Have you cleared the cache since updating the text file? /clearMultiblockCache to empty it, thats required if you want to update the files without reloaded the world.

**Comment by RehabCZ** [comment]
Oh i just took the txt file and put it back into the resources folder and run clear cache command and it works just fine
