### ISSUE TITLE
[RLCraft] the client crashes.

### ISSUE THREAD

**Issue by EnterFor** [fonnymunkey/BQ-RLCraftExpansion#3]
![image](https://user-images.githubusercontent.com/10114685/150674236-ba07181a-660c-4edd-8940-88119d2dfd19.png)
I'm playing RLcraft Modpack,
When I place this item, the client crashes
https://paste.ubuntu.com/p/3tFhb7t8ZM/

**Comment by EnterFor** [comment]
Now the server crashes as soon as I enter, I don't know what to do..
But only the client crashes

**Comment by fonnymunkey** [comment]
This has nothing to do with this mod repository.
